--用户表
CREATE TABLE USERS
(
 USER_ID INT,
 USER_NAME VARCHAR2(20),
 USER_PWD VARCHAR2(20),
 REGTIME DATE,
 CONSTRAINT P_USERS_USER_ID PRIMARY KEY(USER_ID)
)


--员工表
CREATE TABLE EMPLOYEES
(
 EMP_ID INT,
 EMP_NAME VARCHAR2(20),
 SALARY FLOAT,
 HIRE_DATE DATE,
 JOB_ID INT,
 DEP_ID INT,
 MANAGER_ID INT,
 CONSTRAINT P_EMPLOYEES_EMP_ID PRIMARY KEY(EMP_ID),
 CONSTRAINT FK_EMPLOYEES_JOB_ID FOREIGN KEY(JOB_ID) REFERENCES JOBS(JOB_ID),
 CONSTRAINT FK_EMPLOYEES_DEP_ID FOREIGN KEY(DEP_ID) REFERENCES DEPS(DEP_ID)
)

--用户序列
CREATE SEQUENCE SQE_USERs_USER_ID
START WITH 1
INCREMENT BY 1


--用户编号自动写入
CREATE OR REPLACE TRIGGER T_USER_ID
BEFORE INSERT ON USERS FOR EACH ROW
BEGIN
     SELECT SQE_USERs_USER_ID.NEXTVAL INTO  :NEW.USER_ID FROM DUAL;
     SELECT SYSDATE INTO :NEW.REGTIME FROM DUAL;
END;

INSERT INTO USERS(USER_NAME,USER_PWD) VALUES('Admin','0000');

INSERT INTO EMPLOYEES SELECT 
   EMPLOYEE_ID,FIRST_NAME,SALARY,HIRE_DATE,JOB_ID,DEPARTMENT_ID,MANAGER_ID FROM EMPL;

commit;



